Document: odroid-helper
Title: Debian odroid-helper Manual
Author: <insert document author here>
Abstract: This manual describes what odroid-helper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/odroid-helper/odroid-helper.sgml.gz

Format: postscript
Files: /usr/share/doc/odroid-helper/odroid-helper.ps.gz

Format: text
Files: /usr/share/doc/odroid-helper/odroid-helper.text.gz

Format: HTML
Index: /usr/share/doc/odroid-helper/html/index.html
Files: /usr/share/doc/odroid-helper/html/*.html
